export interface TemplateItem {
  label: string;
  prompt: string;
  category: string;
}

export const TEMPLATE_CATEGORIES: { key: string; name: string; icon: string }[] = [
  { key: "portrait", name: "人像", icon: "UserOutlined" },
  { key: "landscape", name: "风景", icon: "PictureOutlined" },
  { key: "scifi", name: "科幻", icon: "RocketOutlined" },
  { key: "ancient", name: "古风", icon: "EnvironmentOutlined" },
  { key: "animal", name: "动物", icon: "BugOutlined" },
  { key: "abstract", name: "抽象", icon: "ExperimentOutlined" },
];

export const TEMPLATES: TemplateItem[] = [
  // 人像
  { category: "portrait", label: "电影级肖像", prompt: "cinematic portrait, professional photography, shallow depth of field, golden hour lighting, bokeh background, 8K, hyperrealistic" },
  { category: "portrait", label: "时尚杂志封面", prompt: "fashion magazine cover, high fashion model, studio lighting, dramatic pose, luxury aesthetic, Vogue style, editorial photography" },
  { category: "portrait", label: "汉服古装", prompt: "traditional Chinese hanfu clothing, ancient Chinese beauty, flowing silk fabric, elegant pose, ink painting background, ethereal atmosphere, soft diffused light" },
  { category: "portrait", label: "赛博朋克人物", prompt: "cyberpunk character, neon lights, futuristic city background, cybernetic enhancements, synthwave color palette, blade runner aesthetic, rain drops" },
  { category: "portrait", label: "日系清新", prompt: "Japanese style portrait, natural lighting, soft colors, youthful, minimalist composition, airy atmosphere, film grain, medium format" },
  { category: "portrait", label: "油画肖像", prompt: "oil painting portrait, classical style, dramatic chiaroscuro lighting, rich textures, Renaissance inspired, detailed brushstrokes" },
  { category: "portrait", label: "黑白纪实", prompt: "black and white documentary portrait, photojournalism style, raw emotion, gritty texture, contrasty lighting, Leica M6, Tri-X 400 film" },
  { category: "portrait", label: "极简白底", prompt: "portrait on pure white background, clean minimal style, bright studio lighting, sharp details, commercial photography, flawless skin" },
  { category: "portrait", label: "复古胶片", prompt: "vintage film portrait, Kodak Portra 400, soft grain, warm tones, 80s aesthetic, natural window light, nostalgic mood" },
  { category: "portrait", label: "未来战士", prompt: "futuristic soldier, advanced armor, sci-fi military, glowing visor, mechanical exoskeleton, dramatic battlefield, epic composition" },

  // 风景
  { category: "landscape", label: "山水水墨画", prompt: "traditional Chinese ink wash painting, misty mountains, waterfall, pine trees, poetic composition, rice paper texture, Zen aesthetic" },
  { category: "landscape", label: "星空银河", prompt: "Milky Way galaxy, starry night sky, long exposure, silhouette mountains, astrophotography, purple and blue tones, cosmic dust" },
  { category: "landscape", label: "日落海滩", prompt: "tropical beach sunset, golden hour, palm trees silhouette, calm ocean waves, warm orange and pink sky, drone photography, paradise" },
  { category: "landscape", label: "樱花街道", prompt: "cherry blossom street, spring season, pink petals falling, sun rays through trees, romantic atmosphere, Tokyo, anime aesthetic" },
  { category: "landscape", label: "赛博朋克城市", prompt: "cyberpunk city skyline, neon signs, flying cars, rainy streets, holographic billboards, Blade Runner 2049 style, night time, reflections" },
  { category: "landscape", label: "北欧森林", prompt: "Scandinavian forest, morning mist, pine trees, moss covered rocks, soft diffused light, nature photography, green tones, tranquility" },
  { category: "landscape", label: "沙漠奇观", prompt: "vast desert landscape, sand dunes, golden hour, dramatic shadows, camel caravan silhouette, Arabian Nights atmosphere, hyperrealistic" },
  { category: "landscape", label: "冬日雪景", prompt: "winter wonderland, snow covered village, warm cabin lights, northern lights aurora, starry sky, Christmas atmosphere, cozy mood" },
  { category: "landscape", label: "城市天际线", prompt: "modern city skyline at blue hour, glass skyscrapers, city lights reflection on water, aerial view, ultra wide angle, sharp details" },
  { category: "landscape", label: "热带雨林", prompt: "dense tropical rainforest, sun rays through canopy, exotic flowers, waterfall, misty atmosphere, vibrant green, nature documentary style" },

  // 科幻
  { category: "scifi", label: "太空站", prompt: "futuristic space station orbiting Earth, massive structure, stars background, sci-fi concept art, detailed mechanical design, 8K, cinematic lighting" },
  { category: "scifi", label: "外星世界", prompt: "alien planet landscape, twin moons, exotic flora, purple atmosphere, sci-fi concept art, strange rock formations, otherworldly beauty" },
  { category: "scifi", label: "赛博朋克街景", prompt: "cyberpunk street scene, neon lights, holographic advertisements, crowded market, rain, steam from vents, Blade Runner aesthetic, night" },
  { category: "scifi", label: "机器人", prompt: "highly detailed robot, mechanical parts, glowing eyes, industrial design, science fiction, 3D render, octane render, photorealistic" },
  { category: "scifi", label: "未来飞行器", prompt: "futuristic aircraft, sleek aerodynamic design, hovering above city, energy shield, blue plasma engine, sci-fi concept art, epic scale" },
  { category: "scifi", label: "全息界面", prompt: "holographic user interface, futuristic HUD, transparent screens, data visualization, cyberpunk style, blue glow, dark background, Iron Man style" },
  { category: "scifi", label: "地下基地", prompt: "secret underground facility, industrial architecture, metal corridors, warning lights, sci-fi horror atmosphere, detailed environment, dramatic lighting" },
  { category: "scifi", label: "时间机器", prompt: "time machine device, steampunk and sci-fi hybrid, glowing core, brass and chrome, intricate gears, laboratory setting, cinematic lighting" },
  { category: "scifi", label: "量子领域", prompt: "quantum realm, microscopic world, energy particles, fractal patterns, glowing threads, subatomic landscape, Ant-Man style, surreal" },
  { category: "scifi", label: "机甲战士", prompt: "giant mecha robot, Japanese anime style, epic battle scene, city destruction, energy beams, detailed mechanical design, dynamic pose" },

  // 古风
  { category: "ancient", label: "工笔花鸟", prompt: "traditional Chinese gongbi painting, detailed flowers and birds, silk texture, vibrant colors, Song dynasty style, fine brushwork, elegant composition" },
  { category: "ancient", label: "敦煌飞天", prompt: "Dunhuang mural style, flying celestial being, flowing ribbons, ancient Chinese art, golden colors, Buddhist imagery, ethereal beauty, cave painting texture" },
  { category: "ancient", label: "武侠江湖", prompt: "Chinese martial arts world, swordmaster on mountain peak, misty landscape, flowing robes, ink painting style, wuxia atmosphere, dramatic composition" },
  { category: "ancient", label: "江南水乡", prompt: "Jiangnan water town, ancient Chinese architecture, stone bridge, willow trees, canal reflection, misty morning, ink wash painting aesthetic, peaceful" },
  { category: "ancient", label: "青花瓷", prompt: "blue and white porcelain pattern, traditional Chinese ceramic art, delicate floral designs, Ming dynasty style, elegant curves, white and cobalt blue" },
  { category: "ancient", label: "宫廷仕女", prompt: "Tang dynasty court lady, traditional Chinese palace, elegant hanfu with intricate embroidery, holding silk fan, classical beauty, historical accuracy" },
  { category: "ancient", label: "书法意境", prompt: "Chinese calligraphy art, black ink on rice paper, bold brush strokes, minimalist, Zen philosophy, artistic composition, cultural heritage" },
  { category: "ancient", label: "竹林七贤", prompt: "ancient Chinese scholars in bamboo forest, traditional ink painting, seven sages, playing guqin, drinking tea, misty atmosphere, literati spirit" },
  { category: "ancient", label: "戏曲脸谱", prompt: "Chinese opera mask, Peking opera style, elaborate facial painting, vibrant colors, dramatic expression, traditional culture, artistic close-up" },
  { category: "ancient", label: "古寺禅意", prompt: "ancient Buddhist temple, morning fog, stone lantern, moss garden, zen meditation atmosphere, Japanese or Chinese style, peaceful solitude" },

  // 动物
  { category: "animal", label: "威武雄狮", prompt: "majestic male lion, golden mane, savanna sunset, regal pose, National Geographic style, wildlife photography, sharp eyes, powerful presence" },
  { category: "animal", label: "灵动猫咪", prompt: "cute cat, expressive eyes, soft fur texture, warm lighting, pet photography, shallow depth of field, playful pose, adorable" },
  { category: "animal", label: "海洋鲸鱼", prompt: "humpback whale breaching ocean surface, dramatic splash, sunset light, massive scale, underwater photography, powerful moment, ocean spray" },
  { category: "animal", label: "雪中狐狸", prompt: "arctic fox in snowy landscape, white fur, winter scene, soft snowflakes, wildlife photography, curious expression, cold atmosphere" },
  { category: "animal", label: "热带鹦鹉", prompt: "colorful macaw parrot, tropical rainforest, vibrant feathers, exotic bird, perched on branch, bokeh background, detailed plumage" },
  { category: "animal", label: "威武雄鹰", prompt: "bald eagle in flight, wings spread wide, sharp talons, dramatic sky, national symbol, wildlife action shot, powerful and free" },
  { category: "animal", label: "深海水母", prompt: "bioluminescent jellyfish, deep ocean, glowing tentacles, ethereal movement, blue and purple light, translucent body, underwater photography" },
  { category: "animal", label: "草原斑马", prompt: "zebra herd, African savanna, golden grass, dramatic sky, wild nature, pattern detail, wildlife documentary style, migration scene" },
  { category: "animal", label: "蝴蝶微距", prompt: "macro photography of butterfly, wing detail, compound eyes, morning dew drops, colorful patterns, flower background, extreme close-up" },
  { category: "animal", label: "熊猫竹子", prompt: "giant panda eating bamboo, Chinese national treasure, cute and peaceful, green forest background, soft lighting, adorable pose" },

  // 抽象
  { category: "abstract", label: "极简几何", prompt: "minimalist geometric composition, clean lines, Bauhaus style, primary colors, balanced asymmetry, vector art, modern design, bold shapes" },
  { category: "abstract", label: "水墨抽象", prompt: "abstract ink wash, black and white, fluid dynamics, organic shapes, sumi-e influence, high contrast, contemporary art, flowing motion" },
  { category: "abstract", label: "宇宙星云", prompt: "abstract nebula, cosmic colors, swirling galaxies, space dust, ethereal light, fractal patterns, purple and blue, interstellar medium" },
  { category: "abstract", label: "液态金属", prompt: "liquid metal chrome, flowing mercury, reflective surface, organic shapes, 3D render, futuristic aesthetic, silver and iridescent, molten texture" },
  { category: "abstract", label: "炫彩粒子", prompt: "colorful particle explosion, rainbow colors, dynamic motion, festival celebration, powder dust, vibrant and energetic, high speed photography" },
  { category: "abstract", label: "故障艺术", prompt: "glitch art, digital distortion, RGB split, corrupted data aesthetic, cyberpunk, VHS effect, modern digital art, colorful noise" },
  { category: "abstract", label: "曼陀罗", prompt: "intricate mandala pattern, sacred geometry, symmetrical design, meditative art, golden ratio, detailed linework, spiritual symbolism" },
  { category: "abstract", label: "玻璃折射", prompt: "glass prism light refraction, rainbow spectrum, crystal clear, optical physics, minimalist setup, white background, caustic light patterns" },
  { category: "abstract", label: "梦幻渐变", prompt: "dreamy gradient blur, soft pastel colors, ethereal atmosphere, abstract background, smooth transitions, vaporwave aesthetic, calming and peaceful" },
  { category: "abstract", label: "金属质感", prompt: "brushed metal texture, industrial abstract, steel and gold, reflective surfaces, macro detail, mechanical precision, modern material study" },
];

/** 中→英 prompt 关键词映射 */
const ZH_EN_MAP: Record<string, string> = {
  "4k": "4K",
  "高清": "high definition",
  "超清": "ultra HD",
  "8k": "8K",
  "高细节": "highly detailed",
  "极致画质": "masterpiece quality",
  "超写实": "hyperrealistic",
  "写实": "photorealistic",
  "照片级": "photorealistic",
  "卡通": "cartoon style",
  "动漫": "anime style",
  "油画": "oil painting",
  "水彩": "watercolor painting",
  "素描": "pencil sketch",
  "水墨": "ink wash painting",
  "浮世绘": "ukiyo-e style",
  "像素": "pixel art",
  "3d渲染": "3D render",
  "赛博朋克": "cyberpunk",
  "蒸汽朋克": "steampunk",
  "极简": "minimalist",
  "复古": "vintage",
  "波普": "pop art",
  "抽象": "abstract",
  "印象派": "impressionist",
  "超现实": "surrealist",
  "哥特": "gothic",
  "巴洛克": "baroque",
  "装饰艺术": "art deco",
  "新艺术": "art nouveau",
  "手绘": "hand-drawn",
  "逆光": "backlight",
  "柔光": "soft lighting",
  "硬光": "hard lighting",
  "自然光": "natural lighting",
  "工作室光": "studio lighting",
  "黄金时刻": "golden hour",
  "蓝调时刻": "blue hour",
  "霓虹灯": "neon lights",
  "烛光": "candlelight",
  "暮光": "twilight",
  "晨光": "morning light",
  "夕阳": "sunset lighting",
  "月光": "moonlight",
  "剪影": "silhouette",
  "伦勃朗光": "Rembrandt lighting",
  "蝴蝶光": "butterfly lighting",
  "侧光": "side lighting",
  "顶光": "top lighting",
  "底光": "bottom lighting",
  "漏光": "light leak",
  "特写": "close-up",
  "大特写": "extreme close-up",
  "中景": "medium shot",
  "全景": "wide shot",
  "远景": "long shot",
  "鸟瞰": "bird's eye view",
  "俯视": "top-down view",
  "仰视": "low angle",
  "平视": "eye level",
  "鱼眼": "fisheye lens",
  "广角": "wide angle",
  "长焦": "telephoto lens",
  "微距": "macro photography",
  "对称构图": "symmetrical composition",
  "三分法": "rule of thirds",
  "引导线": "leading lines",
  "框架构图": "frame within a frame",
  "负空间": "negative space",
  "浅景深": "shallow depth of field",
  "深景深": "deep depth of field",
  "暖色调": "warm color tones",
  "冷色调": "cool color tones",
  "黑白": "black and white",
  "单色": "monochrome",
  "鲜艳": "vibrant colors",
  "柔和": "pastel colors",
  "莫兰迪": "Morandi color palette",
  "赛博色调": "synthwave color palette",
  "大地色": "earthy tones",
  "金色调": "golden tones",
  "银色调": "silver tones",
  "高饱和": "high saturation",
  "低饱和": "desaturated",
  "褪色": "faded colors",
  "霓虹色": "neon color palette",
  "互补色": "complementary colors",
  "类似色": "analogous colors",
  "蓝色调": "blue color grading",
  "橙色调": "orange and teal color grading",
  "原色": "primary colors",
  "史诗": "epic",
  "梦幻": "dreamy",
  "神秘": "mysterious",
  "恐怖": "horror",
  "浪漫": "romantic",
  "忧郁": "melancholic",
  "快乐": "joyful",
  "宁静": "serene",
  "戏剧性": "dramatic",
  "未来感": "futuristic",
  "古典": "classical",
  "自然": "natural",
  "奢华": "luxurious",
  "粗糙": "rough texture",
  "光滑": "smooth texture",
  "毛绒": "fluffy",
  "金属": "metallic",
  "玻璃": "glass",
  "木质": "wooden",
  "布料": "fabric texture",
  "云": "clouds",
  "雾": "fog",
  "雨": "rain",
  "雪": "snow",
  "闪电": "lightning",
  "彩虹": "rainbow",
  "火焰": "flames",
  "烟雾": "smoke",
  "水面倒影": "water reflection",
  "镜头光晕": "lens flare",
  "散景": "bokeh",
  "光斑": "light particles",
  "尘埃": "dust particles",
  "花瓣": "flower petals",
  "羽毛": "feathers",
  "水晶": "crystals",
  "宝石": "gemstones",
  "星空": "starry sky",
  "极光": "aurora borealis",
  "海浪": "ocean waves",
  "电影级": "cinematic",
  "电影质感": "cinematic lighting, film grain",
  "大师级": "masterpiece, best quality",
  "获奖作品": "award winning photograph",
  "锐利": "sharp focus",
  "虚化": "blurred background",
  "景深": "depth of field",
  "高清细节": "intricate details",
  "纹理清晰": "detailed texture",
  "真实感": "photorealistic rendering",
};

export function translateToEnglish(chinesePrompt: string): string {
  let result = chinesePrompt;
  const sortedKeys = Object.keys(ZH_EN_MAP).sort(
    (a, b) => b.length - a.length
  );
  for (const zh of sortedKeys) {
    const en = ZH_EN_MAP[zh];
    result = result.split(zh).join(en);
  }
  return result;
}

export function randomTemplate(): TemplateItem {
  const idx = Math.floor(Math.random() * TEMPLATES.length);
  return TEMPLATES[idx];
}

export function templatesByCategory(category: string): TemplateItem[] {
  return TEMPLATES.filter((t) => t.category === category);
}
